name = "rewards-promo"
main = "src/index.ts"
compatibility_date = "2026-08-04"
workers_dev = true

routes = [
  { pattern = "challenge.ccwu.cc/*", zone_name = "challenge.ccwu.cc" },
  { pattern = "*.challenge.ccwu.cc/*", zone_name = "challenge.ccwu.cc" }
]

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
